### ISSUE TITLE
Can't start guess number game

### ISSUE THREAD

**Issue by olegmitrakhovich** [Kma21/Web-Development--Projects#1]
When I click on guess number game button, the game wont start!!!

**Comment by Kma21** [comment]
I commented out the game button until I complete that feature. https://github.com/Kma21/Web-Development--Projects/pull/2

**Comment by olegmitrakhovich** [comment]
nice please go ahead merge this now.

**Comment by olegmitrakhovich** [comment]
ok I can see it is merged, but the issue is not resolved, but lets close this issue for now and look for another fix.
